### ISSUE TITLE
Permitir abrir links de hipervinculos en una nueva pestaña

### ISSUE THREAD

**Issue by minoveaz** [minoveaz/github-perfil-readme-asombrosos#1]
Al dar click en un link te carga en la misma pagina, la idea seria habilitar la opción de al dar click que se abra en una nueva pestaña

**Comment by dennistobar** [comment]
Hola, creo que no es posible hacerlo a buenas y primeras :(

https://stackoverflow.com/questions/4425198/can-i-create-links-with-target-blank-in-markdown

Si se aplicara el `:target` de la respuesta 2 del hilo, resulta esto...

![Captura de pantalla de 2020-09-24 18-19-54](https://user-images.githubusercontent.com/1218182/94201647-ab400000-fe92-11ea-9473-904caebd81d6.png)

**Comment by minoveaz** [comment]
Efectivamente lo he visto para dejarlo como ejemplo. Si no hay manera la otra opción seria hacer las etiquetas con HTML

**Comment by dennistobar** [comment]
Mira [acá](https://github.com/dennistobar/github-perfil-readme-asombrosos/tree/target_blank) en el link de Thomas, me parece que esos target no son soportados por GitHub en sus sitios :| ([aquí el commit](https://github.com/dennistobar/github-perfil-readme-asombrosos/commit/3fee397eb1653092e9f995876c18a3bcdd5e2d21))

**Comment by minoveaz** [comment]
Vale podriamos hacer el link a los portafolios con etiqueta de html y así funcionaria. Haz el Pull Request.

**Comment by dennistobar** [comment]
Si tienes considerado hacer el awesome-list acá en GitHub creo que no es conveniente, ya que he visto que casi todos están en Markdown. Si no posees esta funcionalidad, mejor dejarlo en MD... ¿qué opinas?

**Comment by minoveaz** [comment]
si es mejor dejarlo en MD,,,,creo que lo dejamos como esta :)
